spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/v1/user/**
                
            - id: promtion-service
              uri: lb://promtion-service
              predicates:
                - Path=/v1/promtions/**
              filters:
                - RewritePath=/v1/promtions(?:/(?<path>.*))?, /${path}

            - id: point-service
              uri: lb://point-service
              predicates:
                - Path=/v1/points/**
              filters:
                - RewritePath=/v1/promotions(?:/(?<path>.*))?, /${path}

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/v1/notifications/**
              filters:
                - RewritePath=/v1/notifications(?:/(?<path>.*))?, /${path}
