spring:
  cloud:
    gateway:
      # 전역 CORS 설정
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*" 
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            # 중복 제거 옵션들
            exposedHeaders: "*"
            maxAge: 3600
      # CORS 응답 헤더 중복 제거 필터
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/user/**
            
        - id: promotion-service
          uri: lb://promotion-service
          predicates:
            - Path=/v1/promotions/**
            
        - id: point-service
          uri: lb://point-service
          predicates:
            - Path=/v1/points/**
            
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v1/notifications/**
            
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/v1/account/**
            
        - id: usergoal-service
          uri: lb://usergoal-service
          predicates:
            - Path=/v1/usergoal/**
            
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/v1/payments/**
            
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/v1/reservations/**
      
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/v1/chats/**
      
        - id: chat-websocket
          uri: lb:ws://chat-service
          predicates:
            - Path=/ws/chat/**

# 디버깅용 로그
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.socket: DEBUG
    reactor.netty: DEBUG
