spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/v1/user/**
                
            - id: promotion-service
              uri: lb://promotion-service
              predicates:
                - Path=/v1/promotions/**

            - id: point-service
              uri: lb://point-service
              predicates:
                - Path=/v1/points/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/v1/notifications/**
                
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/v1/account/**

            - id: usergoal-service
              uri: lb://usergoal-service
              predicates:
                - Path=/v1/usergoal/**
  
